Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Airtime server
  config.vm.define "airtime" do |node|
    node.vm.hostname = "airtime.example.test"
    node.vm.network "public_network", bridge: "eth0"
    # enable audio drivers on VM settings
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id,
                    '--audio', 'pulse',
                    '--audiocontroller', 'hda']
    end
    # Must first install a full kernel to get sound drivers (snd-hda-intel).
    # FIXME: Until I can get the sound to work with VirtualBox VMs, this is not
    # needed...
    #node.vm.provision "shell", run: "once", inline: $BOOTSTRAP_AIRTIME

    # Must include the provision bloc into the last VM so Ansible could
    # provision all VMs at the same time.
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test-vagrant.yml"
      ansible.sudo = true
      # Disable default limit (required with Vagrant 1.5+)
      ansible.limit = 'all'
    end
  end
end

# In order to get ALSA sound drivers, need to upgrade the kernel:
$BOOTSTRAP_AIRTIME = <<EOF
sudo usermod -a -G audio vagrant
if [ ! -e /var/tmp/provisioning_done ]; then
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update
  sudo apt-get install -y linux-image-generic linux-headers-generic
  touch /var/tmp/provisioning_done
  sudo reboot
fi
EOF

# vim: ft=ruby
